name: projetoweb1
description: "Projeto da disciplina web 1"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.3.0 
  file_picker: ^9.0.1
  flutter_html: ^3.0.0-alpha.6
  flutter_widget_from_html: ^0.16.0
  stomp_dart_client: ^2.1.3
  bcrypt: ^1.1.3
  syncfusion_flutter_pdfviewer: ^28.1.37
  cached_network_image: ^3.3.1
  url_launcher: ^6.1.14
  flutter_pdfview: ^1.4.0
  path_provider: ^2.1.5
  flutter_webview_plugin: ^0.4.0
  permission_handler: ^11.4.0
  webview_flutter: ^4.10.0
  image_picker: ^1.1.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

 
